# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd911c69c4e62dde5c34ffdc15ce942570b4f667a93b73bcf38179e521a234141121ab6cf52025c5319da58f46b5a7eb008644cf219bb082fdb3414cf04ea0b

test:
  secret_key_base: be83ac9e68dc85373a1bc391d298b84e9f588a4eee1a2a7ee903419ab03b603d0f3996ce9a4f7d3c0056ebcea1a226f484577d87c49bb603a6a96a310274e503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
